---
- name: Install Docker and required ecosystem packages
  ansible.builtin.apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin", "git"]
    state: present
    update_cache: true

- name: Setup Docker configuration and service
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: Restart Docker

- name: Ensure deployment user is in docker group
  ansible.builtin.user:
    name: "{{ deployment_user }}"
    groups: docker
    append: true