apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bonicare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: compose-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80 # 👈 عدل ده لـ 80 لأن الكونتينر جواه Nginx
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bonicare
spec:
  selector:
    app: frontend
  ports:
  - port: 80         # 👈 بورت السيرفيس الداخلي
    targetPort: 80   # 👈 البورت اللي هيسلم للكونتينر (Nginx)
    nodePort: 30200  # البورت الخارجي اللي بتكتبه في الويندوز
  type: NodePort