apiVersion: v1
kind: Secret
metadata:
  name: bonicare-secret
  namespace: bonicare
type: Opaque
stringData:
  JWT_SECRET: change_me
  JWT_REFRESH_SECRET: change_me
  STRIPE_SECRET_KEY: change_me
  STRIPE_WEBHOOK_SECRET: change_me
  SESSION_SECRET: change_me
  ENCRYPTION_KEY: change_me
