---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Create SSL directory
  ansible.builtin.file:
    path: "{{ nginx_ssl_dir }}"
    state: directory
    mode: '0700'

- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/bonicare.conf"
    mode: '0644'
  notify: 
    - Test Nginx Config
    - Reload Nginx

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true