pipeline {
    agent any
    
    options {
        timestamps()
        ansiColor('xterm')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '10'))
    }

    environment {
        // نستخدم BUILD_NUMBER لضمان عدم الكتابة فوق الصور (Immutable Tags)
        IMAGE_TAG = "${BUILD_NUMBER}"
        GIT_SHA = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
        REGISTRY = "docker.io"
        NAMESPACE = "keroliskhalaf"
    }

    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                git branch: "DevOps-dev", url: 'https://github.com/Antonios-Reda/Team2.git'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_id', usernameVariable: 'D', passwordVariable: 'P')]) {
                    sh 'echo "$P" | docker login -u "$D" --password-stdin'
                }
            }
        }

        stage('Build & Push with Bake') {
            steps {
                // نمرر المتغيرات مباشرة للـ Bake للحفاظ على الـ Tags الموحدة
                sh """
                    docker buildx bake \
                    --push \
                    -f ci/docker-bake.hcl \
                    --set "*.args.VERSION=${IMAGE_TAG}" \
                    --set "*.tags=${REGISTRY}/${NAMESPACE}/bonicare-\$TARGET:${IMAGE_TAG}" \
                    --set "*.tags=${REGISTRY}/${NAMESPACE}/bonicare-\$TARGET:latest"
                """
            }
        }

        stage('Deploy to Production') {
            steps {
                // استدعاء Ansible للنشر مع تمرير الـ Tag الجديد لضمان الـ Rolling Update
                sh """
                    ansible-playbook -i infra/ansible/inventory/prod.ini infra/ansible/deploy.yml \
                    -e "image_tag=${IMAGE_TAG}" \
                    --vault-password-file=.vault_pass
                """
            }
        }
    }

    post {
        failure {
            echo "Deployment failed! Rolling back to last stable version..."
            sh "ansible-playbook -i infra/ansible/inventory/prod.ini infra/ansible/rollback_logic.yml"
        }
        always {
            sh 'docker logout || true'
            cleanWs()
        }
    }
}